name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 src

      - name: Install test requirements
        run: pip install pytest pytest-cov

      - name: Run tests
        run: pytest

      - name: Run coverage
        run: pytest --cov=src --cov-report=xml --cov-fail-under=80

      - name: Generate coverage badge JSON
        run: |
          mkdir -p scripts
          pytest --cov=src --cov-report=xml
          python scripts/generate_coverage_badge.py

      - name: Publish coverage badge to Gist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST /gists \
            -F files[coverage-badge.json]=@coverage-badge.json \
            -F public=false \
            | jq '{ url: .files["coverage-badge.json"].raw_url }' \
            > coverage-badge-url.json

      - name: Test (if tests exist)
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest --maxfail=1 --disable-warnings -q; fi

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag naijapulsebot:ci

      - name: Run revenue report
        run: python scripts/report_revenue.py | tee revenue_report.txt

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: revenue-report
          path: revenue_report.txt 