name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          if [ -f Gemfile ]; then
            bundle install --jobs 4 || true
          fi

      - name: Check _private_posts exists
        run: test -d _private_posts || echo "_private_posts missing – continuing"
        continue-on-error: true

      - name: Check premium exists
        run: test -d premium || echo "premium missing – continuing"
        continue-on-error: true

      - name: Check repo directory exists
        run: test -d repo || echo "repo/ does not exist – continuing"
        continue-on-error: true

      - name: Build Jekyll site
        run: |
          jekyll build --source ./ --destination ./_site
        continue-on-error: true

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 