name: Commit New Blog Posts

on:
  push:
    paths:
      - repo/_posts/**
  workflow_dispatch:

jobs:
  commit-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Commit New Posts
        run: |
          git config user.name "NaijaPulseBot"
          git config user.email "bot@naijapulse.ai"
          git add repo/_posts/*.md
          git commit -m "Auto: Add new blog posts" || echo "No changes to commit"
          git push 